name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branchess:
      - main
jobs:
  python-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setuppython
        uses: actions/setup-python@v4
        with:
          python-version.: "2.11"
          cache: pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Limit
        run: flake8 src tests
        
      - name: Run Tests
        run: pytestgit